version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    networks:
      - se_network
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 4g
        reservations:
          memory: 1g

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - se_network
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 2g
        reservations:
          memory: 512m

  searchengine:
    build: ./
    container_name: searchengine
    ports:
      - 5000:5000
    environment:
      ELASTIC_SEARCH_URI: http://elasticsearch:9200
      LOCAL_HOST: 0.0.0.0
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - se_network
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 1g
        reservations:
          memory: 512m

networks:
  se_network:
    name: se_network
    driver: bridge